/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PRACTICA.HTTP;
import java.util.Scanner;

import com.google.common.net.UrlEscapers;
import java.util.ArrayList;
import org.jsoup.Jsoup;
import java.io.IOException;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import org.jsoup.nodes.FormElement;
import org.jsoup.Connection;

public class App {
  




    public static void main(String[] args) {
        print("PRACTICA #1 - CLIENTE HTTP INTERNET AVANZADO\n");
       Scanner scan = new Scanner(System.in);
        print("Inserte una url: ");
        String url = scan.nextLine();
        print("Parsing...");
        try{
            Connection.Response doc = Jsoup.connect(url).execute();
            Document document =  Jsoup.connect(url).get();
            print("NAME OF THE PAGE: "+ document.title());
            print("A)- LINES: "+ doc.body().split("\n").length);
            Elements parrafos =  document.getElementsByTag("p");
            print("B)- PARAGRAPHS: "+ parrafos.size());
            print("C)- IMG IN PARAGRAPHS: "+ imginparagraph(parrafos));
            Elements form = document.getElementsByTag("form");
            print("D - E)- FORMS: "+  form.size());
            int forms[] = new int [2];;
            forms = clasifyForms(form);
            print("\t GET FORMS: "+ forms[0]);
            print("\t POST FORMS: "+ forms[1]);
            ArrayList<String> in = new ArrayList<String>();
            
            print("\t INPUTS: "+ forms[1]);
            int j = 1, z;

            for(Element fo : form){
                in = inputs(fo);
                print("\t  THE FORM "+ j +", HAS " + in.size()+" INPUTS");
                
                z = 1;
                for(String i : in){
                    print("\t   INPUT "+ z +": "+ i);
                    z++;
                }

                j++;
            }
            print("F)- POST REQUEST: \n"+ post(forms[1], form));
            



        }
        catch(IOException ex){
            System.out.println (ex.toString());
            System.out.println("Could not get the page");
        }


        
    }

    private static int imginparagraph(Elements par){
        /*Esta funcion cuenta las imagenes que estan en los parrafos*/
        int aux = 0;
    
        for(Element p : par){
            aux+= p.getElementsByTag("img").size();

       }


        return aux;
    }

    public static int[] clasifyForms(Elements forms){
        /*Esta funcion es la encargada de clasificar las formas en formas de get o post  */
        int getForms = 0;
        int postForms = 0;
        int f[] = new int [2];
        for(Element form: forms){
            if(form.attr("method").equalsIgnoreCase("GET") || form.attr("method").equals("")){
                getForms++;

            }else if(form.attr("method").equals("POST")){
                postForms++;

            }

        }

        f[0] = getForms;
        f[1] = postForms;
        

        return f;  

    }

    public static ArrayList<String> inputs(Element form){
        /*funcion que retorna los inputs que hay una forma, los devuelve en un array list */
        ArrayList<String> in = new ArrayList<String>();
        String string =  new String();
    
        for(Element input: form.getElementsByTag("input")){
            string =  input.attr("type").toString();
            in.add(string);
        }
    


        return in;
    }

    public static String post(int verify, Elements forms) throws IOException {
        /*Esta funcion hace un post request, y se se pasan por parametro una variable entera 
        que es a cantidad de formas post que hay
        y aprovechando este valor se verifica si hay o no form post a los cuales hacer el request*/
        String respuesta = new String();
        

        if(verify != 0){
            for(Element f : forms){
                Connection.Response res =  ((FormElement)f).submit().data("Internet avanzado", "Practica #1").header("Matricula","20110820").execute();
                respuesta += "\t"+res.body() + "\n";
            }
            

        }else{
            respuesta = "\tTHERE'S NO POST FORMS IN THE DOCUMENT";
        }


        return respuesta;

    }

    public static void print(String string){

        System.out.println(string);
    }

}
